# Generated by Django 4.2.7 on 2024-03-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_college_subject_user_teacher_principal_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'permissions': [('can_change_website', 'Can change website')]},
        ),
    ]
